name: setup-haxeshit
description: "sets up haxe shit, using lix!"
runs:
  using: "composite"
  steps:
      - uses: lix-pm/setup-lix@1.0.0
        with:
          lix-version: 15.8.9 # optional
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
