name: setup-haxeshit
description: "sets up haxe shit, using HMM!"
runs:
  using: "composite"
  steps:
      - uses: krdlab/setup-haxe@v1.1.6
        with:
          haxe-version: 4.2.4
      - uses: actions/cache@v3
        with:
          path: .haxelib/
          key: ${{ runner.os }}-${{ hashFiles('**/hmm.json') }}
      - name: Config haxelib
        run: |
          haxelib config
        shell: bash
      - name: Installing Haxe lol
        run: |
          haxe -version
          haxelib --global install hmm
          haxelib --global run hmm install --quiet
        shell: bash