name: setup-haxeshit
description: "sets up haxe shit, using HMM!"
runs:
  using: "composite"
  steps:
    - uses: funkincrew/ci-haxe@v3
      with:
        haxe-version: 4.3.3
    - name: Config haxelib
      run: |
        haxelib config
      shell: bash
    - name: Installing Haxe lol
      run: |
        haxe -version
        haxelib git haxelib https://github.com/HaxeFoundation/haxelib.git master
        haxelib version
        haxelib --global install hmm
      shell: bash
    - name: dependency install cache
      id: cache-hmm
      uses: actions/cache@v4
      with:
        path: .haxelib
        key: ${{ runner.os }}-hmm-${{ hashFiles('**/hmm.json') }}
    - if: ${{ steps.cache-hmm.outputs.cache-hit != 'true' }}
      name: hmm install
      run: |
        haxelib --global run hmm install
      shell: bash
