name: setup-haxeshit
description: "sets up haxe shit, using HMM!"
runs:
  using: "composite"
  steps:
      - uses: krdlab/setup-haxe@v1.4.0
        with:
          haxe-version: 4.2.5
      - name: Config haxelib
        run: |
          haxelib config
        shell: bash
      - name: Installing Haxe lol
        run: |
          haxe -version
          haxelib install hmm
          haxelib run hmm install --quiet
        shell: bash
