name: build-upload
on:
  workflow_dispatch:
  push:

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "::set-output name=should_run::false"
  create-nightly-html5:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-haxeshit
      - name: Build Lime
        # TODO: Remove the step that builds Lime later.
        # Bash method
        run: |
          LIME_PATH=`haxelib libpath lime`
          echo "Moving to $LIME_PATH"
          cd $LIME_PATH
          git submodule sync --recursive
          git submodule update --recursive
          git status
          sudo apt-get install -y libxinerama-dev
          haxelib run lime rebuild linux --clean
      - name: Build game
        run: |
          sudo apt-get install -y libx11-dev xorg-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libgl-dev libxi-dev libxext-dev libasound2-dev
          haxelib run lime build html5 -debug --times
          ls
      - uses: ./.github/actions/upload-itch
        with:
          butler-key: ${{ secrets.BUTLER_API_KEY}}
          build-dir: export/debug/html5/bin
          target: html5
  create-nightly-win:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false'}}
    runs-on: windows-latest
    permissions:
       contents: write
       actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-haxeshit
      - name: Build Lime
        # TODO: Remove the step that builds Lime later.
        # Powershell method
        run: |
          $LIME_PATH = haxelib libpath lime
          echo "Moving to $LIME_PATH"
          cd $LIME_PATH
          git submodule sync --recursive
          git submodule update --recursive
          git status
          haxelib run lime rebuild windows --clean
      - name: Build game
        run: |
          haxelib run lime build windows -debug
          dir
      - uses: ./.github/actions/upload-itch
        with:
          butler-key: ${{ secrets.BUTLER_API_KEY}}
          build-dir: export/debug/windows/bin
          target: win
