name: build-upload
on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * *'
  push:
    branches:
      - "master"
  
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "::set-output name=should_run::false"
  create-nightly-html5:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-haxeshit
      - name: Build game?
        run: |
          haxelib run lime build html5 -debug --times
          ls
      - uses: ./.github/actions/upload-itch
        with:
          butler-key: ${{ secrets.BUTLER_API_KEY}}
          build-dir: export/debug/html5/bin
          target: html5
  create-nightly-win:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false'}}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore existing build cache for faster compilation
        uses: actions/cache/restore@v3
        id: cache-windows-shit
        with:
          # wha?
          key: cache-build-win
          path: |
            .haxelib/
            export/debug/windows/haxe/
            export/debug/windows/obj/
            
      - name: lix stuff
        run: |
          npm i -g lix
          lix download
      - name: Build game
        run: |
          lix run haxelib run lime build windows -debug --times
          dir
      - uses: ./.github/actions/upload-itch
        with:
          butler-key: ${{ secrets.BUTLER_API_KEY}}
          build-dir: export/debug/windows/bin
          target: win
      - name: Uploading new cache
        uses: actions/cache/save@v3
        with:
          key: ${{ steps.cache-windows-shit.outputs.cache-primary-key }}
          path: |
            .haxelib/
            export/debug/windows/haxe/
            export/debug/windows/obj/
