name: build-upload-html5
on: [push]
jobs:
  create-nightly-html5:
    runs-on: ubuntu-latest
    steps:
      - uses: ninjamuffin99/action-hmm-setup@v1
      - name: Setting up linux
        run: |
          haxelib run lime setup linux
      - name: Build game?
        run: |
          haxelib run lime build html5 -debug -clean
          ls
      - name: Install butler and shit
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Upload game to itch.io
        env: 
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY}}
        run: |
          ./butler login
          ./butler push export/debug/html5/bin ninja-muffin24/funkin-secret:html5-${GITHUB_REF##*/}

