name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1.1.6
        with:
          haxe-version: 4.2.4
      - uses: actions/checkout@v2
      - run: |
          haxe -version
          haxelib install openfl --quiet
          haxelib install lime --quiet
          haxelib install flixel --quiet
          haxelib install flixel-addons --quiet
          haxelib run lime setup linux
