name: learn-github-actions
on: [push]
jobs:
  create-nightly-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1.1.6
        with:
          haxe-version: 4.2.4
      - uses: actions/checkout@v2
      - name: Cache Haxe Stuff
        run: |
        haxelib config
      - name: Installing Haxe Stuff
        run: |
          haxe -version
          haxelib install openfl --quiet
          haxelib install lime --quiet
          haxelib install flixel --quiet
          haxelib install flixel-addons --quiet
          haxelib install hscript --quiet
          haxelib install flixel-ui --quiet
          haxelib install firetongue --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib install hxcpp --quiet
          haxelib git polymod https://github.com/larsiusprime/polymod develop --quiet
          haxelib run lime setup linux
      - name: Build game?
        run: |
          haxelib run lime build html5 -debug -clean
          ls
      - uses: actions/upload-artifact@v1
        with:
          name: funkinSecret-${{ runner.os }}-${{ github.sha }}
          path: export/debug/html5/bin

