name: learn-github-actions
on: [push]
jobs:
  create-nightly-html5:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1.1.6
        with:
          haxe-version: 4.2.4
      - uses: actions/checkout@v2
      - name: Cache Haxe Stuff
        run: |
          haxelib config
      - name: Installing Haxe lol
        run: |
          haxe -version
          haxelib --global install hmm
          haxelib --global run hmm setup
          hmm install --quiet
          haxelib run lime setup linux
      - name: Build game?
        run: |
          haxelib run lime build html5 -debug -clean
          ls
      - name: Install butler and shit
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Upload game to itch.io
        env: 
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY}}
        run: |
          ./butler login
          ./butler push export/debug/html5/bin ninja-muffin24/funkin-secret:html5

